### ISSUE TITLE
GLFW_DOUBLEBUFFER not defined

### ISSUE THREAD

**Issue by cmbruns** [FlorianRhiem/pyGLFW#10]
GLFW_DOUBLEBUFFER should be set to 0x00021010 according to the glfw3.h header at
https://github.com/glfw/glfw/blob/master/include/GLFW/glfw3.h#L646
But I don't see the GLFW_DOUBLEBUFFER symbol anywhere in https://github.com/FlorianRhiem/pyGLFW/blob/master/glfw.py
For the time being I am setting the value locally in my application as a workaround.

**Comment by FlorianRhiem** [comment]
Thank you for reporting this. I added the missing macros and pushed a new version to PyPI. Please let me know if there's anything else missing.
