### ISSUE TITLE
When wanting to use Vulkan as an API, Invalid client API error. 

### ISSUE THREAD

**Issue by Friz64** [FlorianRhiem/pyGLFW#15]
i am writing a vulkan application and when wanting to create the window it tells me

`glfw.GLFWError: (65539) b'Invalid client API'`

i have set the `CLIENT_API` to `NO_API` but somehow it throws an error and i dont know why

**Comment by FlorianRhiem** [comment]
Hello Friz, you might be using an old version of the GLFW shared library, `NO_API` was added in GLFW 3.2, as far as I'm aware. To check this, please post the output of:
```python
import glfw
print(glfw.get_version_string())
```

**Comment by Friz64** [comment]
oh, i was using 3.1.2, sorry for the inconvenience, it works now, thanks!
