### ISSUE TITLE
OSError: dlopen(libglfw3.dylib, 6): image not found -- OSX 10.13

### ISSUE THREAD

**Issue by aarbour** [FlorianRhiem/pyGLFW#16]
On Mac OS 10.13 High Sierra, compiling GLFW does not produce the dylib. In order to create the dylib you need to tell the deployment target version.

export MACOSX_DEPLOYMENT_TARGET=10.8

**Comment by FlorianRhiem** [comment]
I'm a bit confused here, pyglfw doesn't provide the GLFW binaries, except for Windows where the official builds are used.

Did you perhaps mean to create an issue at https://github.com/glfw/glfw? Though I'm pretty sure I've successfully compiled glfw on High Sierra without setting the deployment target.

**Comment by aarbour** [comment]
You're right ... my bad :(

**Comment by FlorianRhiem** [comment]
All good! I just compiled the current master of glfw on High Sierra and it worked fine. Perhaps you forgot to set `-DBUILD_SHARED_LIBS=ON`?
