### ISSUE TITLE
Lacking support for glViewport()

### ISSUE THREAD

**Issue by bendgk** [FlorianRhiem/pyGLFW#22]
I don't see the wrapper for this in any of the branches and when I tried `glfw.gl_viewport(0, 0, 640, 480)` my program crashes to an `AttributeError: module 'glfw' has no attribute 'gl_viewport'`

**Comment by FlorianRhiem** [comment]
Hello Benjamin,

`glViewport` and all other OpenGL functions are not part of GLFW and therefore not provided by this Python wrapper for GLFW. You will want to use an OpenGL wrapper like [PyOpenGL](http://pyopengl.sourceforge.net/) for that. Also, see [What is GLFW not?](http://www.glfw.org/faq.html#what-is-glfw-not) in the GLFW FAQ.

By the way, thanks for your pull request, I'll look into it later today. :)
