### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by einarf** [FlorianRhiem/pyGLFW#27]
Thank for creating this library. 😄 

We're using it now in:
* https://github.com/cprogrammer1994/ModernGL 
* https://github.com/Contraz/demosys-py

pyGLFW seems to perform quite well compated to PyQt5, so it's important to have alternatives.

**Comment by FlorianRhiem** [comment]
Thank you! I can take little credit for the performance, as this is just a wrapper around the awesome glfw doing the heavy lifting, but I'm glad that it's been useful to you! :)

**Comment by einarf** [comment]
I know 😄 I have used GLFW in C/C++ extensively in the past. It's just nice when there is a wrapper ready for it with an active repo owner. pyGLFW was probably one of the easier ones to use because it's so close to the C API and everything translates well in docs.
