### ISSUE TITLE
glfw.init() always pop up new window and make it active

### ISSUE THREAD

**Issue by deepaksharma36** [FlorianRhiem/pyGLFW#32]
Is there any way to set glfw in way that glfw.init() pop up the new window in the background and does not make it the active window.

**Comment by FlorianRhiem** [comment]
You can control some window behavior using the [glfw window creation hints](https://www.glfw.org/docs/latest/window.html#window_hints).

You can use `glfw.window_hint(glfw.FOCUSED, False)` before creating a window to make sure it will not take the input focus from the current window. On macOS, this opens the window behind the current window, but in front of some other background windows.

If that isn't enough, you could iconify the window right away using `AUTO_ICONIFY`.

**Comment by FlorianRhiem** [comment]
Did this solve your issue?

**Comment by deepaksharma36** [comment]
Yes! Thanks for the suggestion.
