### ISSUE TITLE
glfw mac binaries

### ISSUE THREAD

**Issue by christopherhesse** [FlorianRhiem/pyGLFW#35]
Hi!  Thanks for making these bindings!  It looks like glfw now releases mac binaries on the official site: https://www.glfw.org/download.html

Would you have any interest in including these in a mac-specific wheel so that users can get started easily?

**Comment by FlorianRhiem** [comment]
Hello Christopher,
thank you for letting me know about those binaries, I'll definitely use them for macOS wheels.

**Comment by FlorianRhiem** [comment]
I've added macOS wheel creation to the GitLab CI config and uploaded macOS wheels for 1.8.5.

**Comment by cshesse** [comment]
Oh wow, thanks!
