### ISSUE TITLE
ctypes.ArgumentError in glfwGetMonitorContentScale

### ISSUE THREAD

**Issue by pfaion** [FlorianRhiem/pyGLFW#38]
Hi, I'm getting the following error when calling `glfwGetMonitorContentScale`:
```
... (traceback in my code) ...

  File "/home/pfa/.pyenv/versions/3.6.9/lib/python3.6/site-packages/glfw/__init__.py", line 937, in get_monitor_content_scale
    _glfw.glfwGetMonitorContentScale(monitor, xscale, yscale)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_c_float instance instead of LP_c_int
```
It seems that pyGLFW is trying to call the ctypes function with ints, but glfwGetMonitorContentScale requires floats: https://www.glfw.org/docs/latest/group__monitor.html#gad3152e84465fa620b601265ebfcdb21b

Im using GLFW 3.3 and pyGLFW 1.8.6 on Ubuntu 18.04.

**Comment by FlorianRhiem** [comment]
Hello Patrick, thank you for reporting this bug! I've fixed it and released a new version as 1.8.7.
