### ISSUE TITLE
Support to get native Window id's

### ISSUE THREAD

**Issue by almarklein** [FlorianRhiem/pyGLFW#39]
Hey! we're building a [Python wrapper](https://github.com/almarklein/wgpu-py) around the [wgpu lib](https://github.com/gfx-rs/wgpu), and would like to use glfw as a lightweight alternative to provide a window.

However, to make things work, I need to provide wgpu with a native window id so it can create a surface object. It looks like glfw in principal supports this via e.g. [glfwGetWin32Window](https://www.glfw.org/docs/latest/group__native.html).

Any idea how feasible it is to expose this via the Python API?

Thanks!

**Comment by FlorianRhiem** [comment]
Hey Almar,
sure, I can add wrappers for the native access functions, though I won't get to it until after the holidays. Until then, you should be able to use the following as a quick wrapper for `glfwGetWin32Window`:

```python
import ctypes
import glfw

glfw._glfw.glfwGetWin32Window.restype = ctypes.c_void_p
glfw._glfw.glfwGetWin32Window.argtypes = [ctypes.POINTER(glfw._GLFWwindow)]

def get_win32_window(window):
    return glfw._glfw.glfwGetWin32Window(window)
```

**Comment by almarklein** [comment]
No rush! That solution works like a charm, and I can get away with that just fine. Thanks a lot!

(I'll leave it up to you whether to close this or not.)

**Comment by FlorianRhiem** [comment]
I've added wrappers for all native functions as part of release 1.9.0.
