### ISSUE TITLE
glfw is actually easy to install on most Linuxes

### ISSUE THREAD

**Issue by almarklein** [FlorianRhiem/pyGLFW#43]
The readme says that Linux users must compile GLFW from source, which might put people off. At least on Ubuntu it's just `apt install libglfw3` (or `libglfw3-wayland`).

**Comment by FlorianRhiem** [comment]
Thank you for the suggestion, this is especially useful now that there are wheels for Linux. I've updated the text and also removed the reference from macOS to Linux, instead duplicating the small paragraph and using `DYLD_LIBRARY_PATH` in the macOS version.

**Comment by almarklein** [comment]
> now that there are wheels for Linux.

🎆

**Comment by FlorianRhiem** [comment]
Yeah, they aren't "proper" manylinux2010 wheels as GLFW depends on more X11 libraries than manylinux2010 allows, but they're close enough that users on a system with an X11-based desktop environment should be fine without installing GLFW themselves. Of course that doesn't handle Wayland, osmesa, etc, but it's a good step in the right direction and makes the installation fairly easy for a lot of Linux users.
