### ISSUE TITLE
glfw.set_window_opacity :: TypeError: this function takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by mahroni-14** [FlorianRhiem/pyGLFW#51]
Getting error when trying to call **glfw.set_window_opacity**. Here is the **traceback** significant  part ->

  File "/home/roni/.pyenv/versions/3.8.3/lib/python3.8/site-packages/glfw/__init__.py", line 1337, in set_window_opacity
    _glfw.glfwSetWindowOpacity(window)
TypeError: this function takes at least 2 arguments (1 given)

**Maybe the second param was missed somehow**.
I fixed it with passing the second param manually and it works.

**Comment by FlorianRhiem** [comment]
Hello, thank you for reporting this issue!

I've fixed it and released version 1.11.2 with the fix.
