### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by crackwitz** [FlorianRhiem/pyGLFW#6]
glfw.py, line 140: add this:

    if _glfw is None:
        _glfw = ctypes.CDLL("glfw3.dll")

I can't make much sense of the detection code that's there. It looks like it should pick up a .dll, but it didn't.

**Comment by FlorianRhiem** [comment]
I mostly work on Linux and OS X. As far as I know ctypes.CDLL works a good bit different on Windows. Please verify whether 219c551 solves the problem for you.

**Comment by crackwitz** [comment]
219c551 works (for me ;).

CDLL just picks it up from any path in %PATH%. That's normal behavior for Windows.

**Comment by FlorianRhiem** [comment]
Great. Yeah, I thought so. I wrote that detection code as ctypes.CDLL did not find the library by name alone. Oddly I just tried it on OS X and linux and it seemed to work. I'll look into it the next couple of days and maybe I can toss out most of the detection code and just try a couple of the common library names.
Thank you!
