### ISSUE TITLE
M1 MacBook Conda install issue

### ISSUE THREAD

**Issue by slerman12** [FlorianRhiem/pyGLFW#60]
Installed via pip (`pip install glfw`) but when I run

```
python
>>>import glfw
```

I get this error:

```
_default_error_callback = _GLFWerrorfun(_handle_glfw_errors)
MemoryError
```

Not sure what's going on.

Just also tested deactivating my conda env and installing/running in a simple vanilla python virtualenv and the import worked but I need it through Conda.

Is there a conda incompatibility?

**Comment by FlorianRhiem** [comment]
Hey @slerman12, I do not have an M1 mac, so I have no way to check or debug directly, but I suspect it might be this issue: https://bugs.python.org/issue42688 If that's the case, you will need to use a python version containing those fixes.

Please try to run the following code, to see if this alone already causes the MemoryError:

```python
import ctypes

@ctypes.CFUNCTYPE(None, ctypes.c_int, ctypes.c_char_p)
def test(a, b):
	print(a, b)
```

**Comment by slerman12** [comment]
Yes, it does.

**Comment by FlorianRhiem** [comment]
Then I think your best bet is to check if using Python 3.10.1 fixes this issue, if you're not already using that. I can't help you otherwise, as pyGLFW is a ctypes-based wrapper and ctypes itself seems to be having this issue.
