### ISSUE TITLE
Full screen print screen on Windows 10 only captures first frame

### ISSUE THREAD

**Issue by Qlii256** [FlorianRhiem/pyGLFW#65]
When using Windows' print screen functionality (Print Screen, Win + Print Screen, Alt + Print Screen), only the very first rendered frame is captured. This only seems to happen in full screen mode and not in windowed mode.

I've been asking around and might be related to double/triple buffering on the driver side of things. Not sure if anything can be done about this?

**Comment by FlorianRhiem** [comment]
Hey @Qlii256,

this repository is for pyGLFW, a Python wrapper for GLFW. The repository you should check out is the actual repo for GLFW: https://github.com/glfw/glfw/, though you might also want to check out their [Discourse server](https://discourse.glfw.org/) as suggested by their [Community](https://www.glfw.org/community.html) page.
