### ISSUE TITLE
MOUSE_PASSTHROUGH attr issue

### ISSUE THREAD

**Issue by OpsecGuy** [FlorianRhiem/pyGLFW#68]
Hey,

Today I tried to use MOUSE_PASSTHROUGH variable as window hint, but looks like it does not working correctly and attr can not be found even if vs code gives typo hint for that variable.

https://i.imgur.com/NgOumea.png

**Comment by FlorianRhiem** [comment]
Hey @OpsecGuy,
`GLFW_MOUSE_PASSTHROUGH` will be part of the (as of yet unreleased) GLFW version 3.4, as such it isn't available yet. If you build a development version of GLFW, you can use it with pyGLFW by either setting the `PYGLFW_PREVIEW` environment variable or by installing [glfw-preview](https://pypi.org/project/glfw-preview/).
