### ISSUE TITLE
Is the latest release broken?

### ISSUE THREAD

**Issue by almarklein** [FlorianRhiem/pyGLFW#77]
The release notes say:

> GLFW 3.4 is not included in Python wheels for glfw 2.7.0, due to issues building GLFW 3.4 on the corresponding systems, e.g. manylinux 2014.

What are the implications of this? Does it include an older glfw lib?

**Comment by FlorianRhiem** [comment]
The wheels contain GLFW 3.3.9, as both 3.3.10 and 3.4 rely on features not available in the build systems for those wheels, manylinux2014 and manylinux2010. You can view the way the wheels are built [in the GitLab CI config](https://github.com/FlorianRhiem/pyGLFW/blob/master/.gitlab-ci.yml) and I have opened an [issue](https://github.com/glfw/glfw/issues/2495) about this, as a workaround reported in an older issue about this problem leads to a second problem by now.

The new release moves all definitions/macros and functions introduced in GLFW 3.4 from only being available in the preview to being available in general, if the loaded GLFW implementation supports it (i.e. if the function symbol can be loaded). This can be useful for users with a GLFW library of their own or from their system. As the code still checks whether the function symbols are available, the wheels for this release should **not** be broken, but please let me know if you encounter any issues.

**Comment by almarklein** [comment]
Thanks for the detailed explanation!
