### ISSUE TITLE
make_context_current and get_current_context differ

### ISSUE THREAD

**Issue by Qlii256** [FlorianRhiem/pyGLFW#82]
I'm trying to build an application that rendres multiple windows on the screen, each running in their own threads. I've ran into some issues related to OpenGL calls failing due to I believe the wrong context. After some troubleshooting I've found out that even when not multi threading and just having a single window/context created, the glfw.make_context_current does not seem to work.

The following code gives the output below:

**CODE**

    import glfw

    if __name__ == '__main__':
        glfw.init()
        window = glfw.create_window(800, 600, 'test', None, None)

        print(window)
        glfw.make_context_current(window)
        print(glfw.get_current_context())`

**OUTPUT**

    <glfw.LP__GLFWwindow object at 0x000002517A61A240>
    <glfw.LP__GLFWwindow object at 0x000002517A61A3C0>

    Process finished with exit code 0

As you can see, both window objects' ids are different, which is unexpected behaviour. The current context should be the one I've just set using make_context_current.

**Comment by FlorianRhiem** [comment]
Hey @Qlii256,
the [code](https://github.com/FlorianRhiem/pyGLFW/blob/7a683c3db9bb882c833d13233e22ec65b4edb3c7/glfw/__init__.py#L2348) for the wrapper of those two functions is fairly simple:

```python
_glfw.glfwMakeContextCurrent.restype = None
_glfw.glfwMakeContextCurrent.argtypes = [ctypes.POINTER(_GLFWwindow)]
def make_context_current(window):
    """
    Makes the context of the specified window current for the calling
    thread.

    Wrapper for:
        void glfwMakeContextCurrent(GLFWwindow* window);
    """
    _glfw.glfwMakeContextCurrent(window)

_glfw.glfwGetCurrentContext.restype = ctypes.POINTER(_GLFWwindow)
_glfw.glfwGetCurrentContext.argtypes = []
def get_current_context():
    """
    Returns the window whose context is current on the calling thread.

    Wrapper for:
        GLFWwindow* glfwGetCurrentContext(void);
    """
    return _glfw.glfwGetCurrentContext()
```

What happens internally (in ctypes code rather that in pyGLFW code) in `get_current_context` is that the pointer returned by the C library is wrapped in a ctypes pointer object, which represents the pointer in Python. We can get the address associated with that pointer using `ctypes.addressof`, e.g. `ctypes.addressof(window.contents)`, or (a bit more convolutedly) by casting the pointer to a void pointer and accessing its value, e.g. `ctypes.cast(window, ctypes.c_void_p).value`. This way we can confirm that both pointers in fact point to the same address. While comparing the equality of this address will work, comparing the pointers themselves will not work, as ctypes types do not use their value for equality checks, e.g. `ctypes.c_int(1) == ctypes.c_int(1)` is false.

Which is a fairly long-winded explanation to say: the functions return ctypes pointer objects to the same address, which sadly behave in a way that is different to C pointers and unintuitive here.

**Comment by Qlii256** [comment]
@FlorianRhiem Thank you. So it's normal to have different id's then. I'm still having an issue where sometimes making context current fails for some reason.

**Comment by FlorianRhiem** [comment]
As the Python wrapper is about as minimal as it can be for these functions, I doubt that the wrapper causes these context changing issues. Can you provide a minimal working example of the bug? In that case we could check if it behaves differently in C. I don't expect so, but that would also be a good step towards reporting the issue to GLFW itself.

**Comment by Qlii256** [comment]
The problems seems to be when I'm making the context current in any thread, it sometimes fails while I'm in the process of resizing the window. When resizing the window it somtimes gives me a GLFW warning (not an exception) that it failed to make the context current. This causes all sorts of OpenGL errors because it has not current context. I managed to "fix" it by either not rendering that frame or trying to make the context current again (works most of the time).

GLFWError: (65544) b'WGL: Failed to make context current: The requested transformation operation is not supported. '
  warnings.warn(message, GLFWError)

**Comment by FlorianRhiem** [comment]
That indeed seems like an issue with [GLFW itself](https://github.com/glfw/glfw) rather than with this wrapper, or perhaps with WGL, as it seems the error stems from there. Good luck, though!
